spring:
  application:
    name: 08_springboot_jpa
  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
