#spring.application.name=03-hello-springboot
#server.port=9090
spring:
  application:
    name: 03_hello_springboot
server:
  port: 9090

logging:
  level:
    com.course: trace
  file:
    path: C:\Users\redca\log\
